### ISSUE TITLE
Add hooks and settings for extensions

### ISSUE THREAD

**Issue by adambullmer** [turkus/live-premailer#7]
We use `gettext` in our emails for localization. Currently I cannot use this really fantastic library because this extension cannot be included.

As used In my template:
```
{{ gettext("text to be translated") }}
{{ _("_ is an alias for gettext") }}
```

With either of those in my template, I cannot successfully run `lpremailer init [--force]` as is fails to find gettext in the environment.

```
Traceback (most recent call last):
  File "/Users/adam/.virtualenvs/sample-project/bin/lpremailer", line 11, in <module>
    sys.exit(main())
  File "/Users/adam/.virtualenvs/sample-project/lib/python2.7/site-packages/lpremailer/main.py", line 314, in main
    LivePremailer().run()
  File "/Users/adam/.virtualenvs/sample-project/lib/python2.7/site-packages/lpremailer/main.py", line 298, in run
    self.json_files()
  File "/Users/adam/.virtualenvs/sample-project/lib/python2.7/site-packages/lpremailer/main.py", line 267, in json_files
    JsonGenerator(handler, HERE).generate()
  File "/Users/adam/.virtualenvs/sample-project/lib/python2.7/site-packages/lpremailer/utils.py", line 128, in generate
    self.create_file()
  File "/Users/adam/.virtualenvs/sample-project/lib/python2.7/site-packages/lpremailer/utils.py", line 121, in create_file
    json.dump(self.feed(), fjson, indent=4)
  File "/Users/adam/.virtualenvs/sample-project/lib/python2.7/site-packages/lpremailer/utils.py", line 109, in feed
    self.handler.prepare_html()
  File "/Users/adam/.virtualenvs/sample-project/lib/python2.7/site-packages/lpremailer/main.py", line 181, in prepare_html
    self.html = template.render()
  File "/Users/adam/.virtualenvs/sample-project/lib/python2.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/Users/adam/.virtualenvs/sample-project/lib/python2.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 767, in top-level template code
  File "/Users/adam/.virtualenvs/sample-project/lib/python2.7/site-packages/jinja2/ext.py", line 134, in _gettext_alias
    return __context.call(__context.resolve('gettext'), *args, **kwargs)
jinja2.exceptions.UndefinedError: 'gettext' is undefined
```

I've tried ignoring that parse error and overriding both method in the `_dev.json` as seen below, but doing that doesn't compile a `_live` template, and doesn't yield any console errors either. (The browser opens the server page just fine).

```json
{
  "_": "lambda x: x",
  "gettext": "lambda x: x"
}
```

I think to fully support this (and others) there would need to be an exposed setting of extensions that would get passed to the j2 environment. The trickier part would be a hook into the initialization where arbitrary code could be executed, possibly in the form of an include and execute, passing in the `j2_env` to the function so a consumer can specify whatever they need. However in the short term, my code below does resolve my specific issue.

An example of my specific use case would be:
https://github.com/turkus/live-premailer/blob/master/lpremailer/main.py#L46
```py
# pip install Babel==2.5.3
from babel.support import Translations

# ... L46 __init__()
        self.j2_env = Environment(loader=self.j2_loader, extensions=["jinja2.ext.i18n"])
        # Required minimal additions to install the extension.
        # Maybe call user_specified_func_here(self.j2_env)
        translations = Translations.load()
        self.j2_env.install_gettext_translations(translations)
```

Link to jinja2 i18n docs: http://jinja.pocoo.org/docs/2.10/extensions/#i18n-extension

**Comment by adambullmer** [comment]
This appears to work mostly fine on python 3.6.3. Creating the json file is a little buggy, but manually placing them in there works, unlike my example above. This fails on a `{{ _("translate me") }}` node.

```
Traceback (most recent call last):
  File "/Users/adam/.virtualenvs/sample-project/bin/lpremailer", line 11, in <module>
    sys.exit(main())
  File "/Users/adam/.virtualenvs/sample-project/lib/python3.6/site-packages/lpremailer/main.py", line 315, in main
    LivePremailer().run()
  File "/Users/adam/.virtualenvs/sample-project/lib/python3.6/site-packages/lpremailer/main.py", line 299, in run
    self.json_files()
  File "/Users/adam/.virtualenvs/sample-project/lib/python3.6/site-packages/lpremailer/main.py", line 268, in json_files
    JsonGenerator(handler, HERE).generate()
  File "/Users/adam/.virtualenvs/sample-project/lib/python3.6/site-packages/lpremailer/utils.py", line 128, in generate
    self.create_file()
  File "/Users/adam/.virtualenvs/sample-project/lib/python3.6/site-packages/lpremailer/utils.py", line 121, in create_file
    json.dump(self.feed(), fjson, indent=4)
  File "/Users/adam/.virtualenvs/sample-project/lib/python3.6/site-packages/lpremailer/utils.py", line 112, in feed
    tokenize(node, results)
  File "/Users/adam/.virtualenvs/sample-project/lib/python3.6/site-packages/lpremailer/utils.py", line 45, in tokenize
    tokenize(item, _dict)
  File "/Users/adam/.virtualenvs/sample-project/lib/python3.6/site-packages/lpremailer/utils.py", line 65, in tokenize
    root, key, last = tokenize(node.node, _dict_call)
TypeError: 'NoneType' object is not iterable
```

**Comment by turkus** [comment]
@adambullmer great thanks for the issue! I'm really sorry for a delay in the response, but I realized that had disabled notifications here (damn it!). I have to enable it. But to the point. I'll try to solve it. Keep in touch.

**Comment by turkus** [comment]
@adambullmer currently only `i18n` has been enabled. I think that's the most used extension in making email templates. If you need something more, just let me know :)
